### ISSUE TITLE
Retrieve DigiBird blogposts

### ISSUE THREAD

**Issue by rasvaan** [rasvaan/digibird#14]
Create a connection to the SEALINCMedia wordpress site (https://sealincmedia.wordpress.com) and retrieve the posts labelled with DigiBird. Discuss what the best place would be for this code (middleware folders?). See if password is needed and discuss how this password can be safely stored (read: not on github).

**Comment by LaraHack** [comment]
See:
https://github.com/kadamwhite/wordpress-rest-api, but requires https://github.com/WP-API/WP-API
https://github.com/scottgonzalez/node-wordpress
